### ISSUE TITLE
LOG_ERROR_LEVEL error at the bottom of pages

### ISSUE THREAD

**Issue by paulbohman** [Jako/SwitchTemplate#3]
When I'm using SwitchTemplate, the switching works fine, but I get this error message at the bottom of every page:

Fatal error: Undefined class constant 'LOG_LEVEL_ERROR' in [server path]/core/model/modx/error/moderrorhandler.class.php on line 99

No matter which template I switch to, and no matter how simple the template is, I get the same error.

**Comment by paulbohman** [comment]
I'm using MODX 2.5.2 with SwitchTemplate 1.1.0-pl

The error happens even on this template:

<!DOCTYPE html>
<html lang="en" >
<head>
<title>[[*pagetitle]]</title>
<base href="[[++site_url]]">
</head>
<body>
[[*content]]
</body>
</html>

**Comment by Jako** [comment]
Do you have any plugins installed, that are running in the installation?

LOG_LEVEL_ERROR is a constant of xPDO and modX extends xPDO, so there must be a strange configuration on your server. Which PHP version are you using?

Maybe the fatal error could be fixed with 
```
$this->modx->log(xPDO::LOG_LEVEL_ERROR, $errmsg, '', '', $errfile, $errline);
```
in line 99 of /core/model/modx/error/moderrorhandler.class.php and the recoverable error could be logged.

**Comment by Jako** [comment]
Closing this because waiting for an answer for about 3 months. Feel free to reopen the issue.
